name: Build and Deploy to Yandex Cloud Serverless Containers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        # env:
        #   CR_REGISTRY: ${{ env.REGISTRY_ID }}
        #   CR_REPOSITORY: ${{ env.CONTAINER_NAME }}
        #   IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "REGISTRY_ID: '${{ env.REGISTRY_ID }}'"
          echo "CONTAINER_NAME: '${{ env.CONTAINER_NAME }}'"

          IMAGE_NAME="cr.yandex/${{ env.REGISTRY_ID }}/${{ env.CONTAINER_NAME }}:${{ github.sha }}"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy Serverless Container
        id: deploy-sls-container
        uses: yc-actions/yc-sls-container-deploy@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          revision-service-account-id: ajeqnasj95o7********
          revision-image-url: cr.yandex/crp00000000000000000/my-cr-repo:${{ github.sha }}
          container-name: yc-action-demo
          folder-id: bbajn5q2d74c********
          revision-cores: 1
          revision-memory: 512Mb
          revision-core-fraction: 100
          revision-concurrency: 8
          revision-execution-timeout: 10
